title:            Committed.
locale:           en_US
description:      ...a story of things I've put in version control
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://dwink.github.io
disqus_shortname: committedcode

# Owner/author information
owner:
  name:           David Harks
  avatar:         http://www.gravatar.com/avatar/f9652452815573245b3f22eed401133d.png
  bio:            "There are few things in life more satisfying than solving a great problem."
  email:          dave@dwink.net
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github: dwink
  stackoverflow: 319309
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
